Bump pre-commit version to current
This fixes the following error from ansible-lint:

...
  File "/home/runner/.cache/pre-commit/repory1hpslb/py_env-python3.9/lib/python3.9/site-packages/ansible_compat/prerun.py", line 13, in get_cache_dir
    basename = project_dir.resolve().name.encode(encoding="utf-8")
AttributeError: 'str' object has no attribute 'resolve'

This is because ansible-lint doesn't support the new api from ansible-compat v4
see also https://github.com/ansible/ansible-compat/issues/258#issuecomment-1533054345